### PR TITLE
Use bleeding edge dependency to fix Firefox support

### PR DESCRIPTION
**Pull request by fregante**
Fixes https://github.com/juliangruber/browser-run/issues/145
Fixes https://github.com/juliangruber/tape-run/issues/77

Let's wait a bit for the original dependency to be published to npm instead. This is only for testing purposes.

Tests are failing and will be fixed by #148

### CODE REVIEW

**Comment by fregante** [comment]
There’s no repo, I just downloaded a zip and pushed it. Perhaps I should point the “homepage” to this issue.

**Comment by juliangruber** [comment]
Please fork it and create a repo, otherwise it's impossible to review the module's source without first downloading it

**Comment by fregante** [comment]
There's no point in that. Our source already exists online and it's https://github.com/substack/browser-launcher/tree/603e1eae210cf43bee9aae5f18d4cf9006e600db

I can include this specific link in there but the readme already explains the situation.

**Comment by fregante** [comment]
It's not a fork, it's the same package under a different name. Having a repo online doesn't guarantee that the published package has the same code, so if "reviewing the module's source" is for security purposes then you should download the source from npm itself.

**Comment by juliangruber** [comment]
If the readme explains it, as it does now, and links to the source, as it also does now, that's all I needed :+1:

**Comment by juliangruber** [comment]
Actually no, looking at the pr, where is the commit that makes this `1.0.2-2` on npm? If the code differs between waht's on npm and what's at the source (github), that's a security risk. Please link to a fork where all commits are available.

**Comment by juliangruber** [comment]
Also, https://www.npmjs.com/package/browser-launcher-temp does _not_ contain a link to the source! It only links back to this PR, while it should link to https://github.com/substack/browser-launcher/tree/603e1eae210cf43bee9aae5f18d4cf9006e600db instead. Please as mentioned above link to your fork with the release commit.

**Comment by fregante** [comment]
I’m not gonna publish a repo for the aforementioned reasons

**Comment by ashnur** [comment]
All this politics is sad :) Can't we have the link fixed in README? I also hate when I can't reach the source of the code that's on npm. 
If nothing works I am willing to create the damn fork, just need a bit of orientation because  I haven't yet had the time to read the source, only the discussion in this issue.

**Comment by juliangruber** [comment]
> I’m not gonna publish a repo for the aforementioned reasons. Feel free to close this PR and publish a fork (repo and npm) if necessary in your view

I don't understand where the resistance is coming from. In my mind this is a relatively straight forward procedure:

1) hit the `fork` button on the original repo
2) create a branch from the PR branch which you want to publish
3) update `README` and `package.repository` to point to your fork
4) `npm version patch && git push --tags && git push && npm publish`

The reason it's important for me that the exact npm code and tags can be found on github is that this makes module review a lot easier, you have a point of reference, and npm security tooling (like NCM which I've worked on) will otherwise decline your module for its source not matching its repository. There are _so_ many modules in our dependency trees, let's not make it harder for ourselves by obscuring the actual source.

**Comment by juliangruber** [comment]
@fregante I have removed you as a collaborator from this project. If you're not happy with how I maintain my projects and don't convince me what I'm doing wrong, you're free to collaborate some place else, or as an independent contributor.

**Comment by fregante** [comment]
Again, it’s not a fork. It’s the same package under a different name. Temporarily. It’s an alias.

**Comment by juliangruber** [comment]
where is the commit that bumps its version?

**Comment by juliangruber** [comment]
I know the PR won't contain that commit, which is why I think a fork is the only safe way to publish this

**Pull request closed without merging**
