### PR TITLE
Electron update for Apple M1 support

### PR DESCRIPTION
**Pull request by fanatid**
This is temporary PR with a demonstration that things work. Once dependencies will be released PR will be updated.

Tracked PR:
- [x] https://github.com/juliangruber/electron-stream/pull/38
- [x] https://github.com/substack/browser-launcher/pull/52
- [x] https://github.com/substack/browser-launcher/pull/53

### CODE REVIEW

**Comment by fanatid** [comment]
Dependencies updated. Tested locally on v10.0.0 (lowest version from `.travis.yml`) on linux-x64.

**Comment by juliangruber** [comment]
Nice work, is this good to go then?

**Comment by fanatid** [comment]
Well, local tests are passed now  :)
I still trying to compile wasm in my another PR (https://github.com/bitcoinjs/tiny-secp256k1/pull/53) and did not run tests there yet. If you want I can leave a comment here once will able to run tests with `browser-run`.

**Comment by juliangruber** [comment]
Alright, I think this should be fine, but ping me nevertheless please :)

**Comment by juliangruber** [comment]
https://github.com/juliangruber/browser-run/releases/tag/v10.0.0

**Comment by fanatid** [comment]
I was able to run my tests with `browser-run` on M1. Thanks again!

**Pull request merged**
