### PR TITLE
Drop PhantomJS support

### PR DESCRIPTION
**Pull request by fregante**
PhantomJS was [discontinued in March 2018](https://github.com/ariya/phantomjs/issues/15344); the last release was in 2016.

It's currently [breaking the tests](https://travis-ci.org/juliangruber/browser-run/builds/623683013) for unknown reasons and it's not worth investigating.

When merged, this will be released as a breaking.

### CODE REVIEW

**Comment by fregante** [comment]
I’m kind of hoping to restore Firefox support in v6 before releasing v7, sadly we depend on another package to fix that. The only way to expedite this is for me to publish a temporary fork of `browser-launcher` and use it as a dependency in #149. What do you think?

**Comment by juliangruber** [comment]
Btw, I created https://github.com/juliangruber/just-launch as a replacement for browser-launcher, but haven't gotten around rewriting this module on top of it. Maybe you could pick that up?

**Comment by fregante** [comment]
@juliangruber that's a nice little module. I think it would be a breaking release though, so what if we release v6.0.1 with https://github.com/juliangruber/browser-run/pull/149 (BUT NOT this PR) and then later someone can use `just-launch` and publish v7? This would keep everything on v6 working (or it would restore existing installations) before moving onto the next version.

In short:
1. `git push origin b46c09c:master --hard` locally, so you undo this PR
1. Merge #149 
1. `npm version 6.0.1`
1. `npm publish`
1. `git pick d353cb5` so this PR is applied on top
1. `git push` to push everything to the repo

Then, when `just-launch` is added (or whatever the next release will be) you can publish it as v7

**Comment by juliangruber** [comment]
> @juliangruber that's a nice little module. I think it would still be a breaking release though. I'd rather make v6 first for existing users before moving onto the next version.

I agree that it would be a breaking change and let's finish other work first.

> What if we release v6.0.1 with:

Left a change request, otherwise :+1:

> In short:

Why do you want to undo this PR? And please don't force push on a shared repo.

**Comment by fregante** [comment]
I felt it would be easier to explain like that, but the point is releasing 6.0.1 without the PhantomJS commit. How you do that is up to you

**Comment by juliangruber** [comment]
Why don't we just release 7.0.0 with the phantomjs commit and continue from there? It has landed anyway, people should be ok with upgrading.

**Comment by fregante** [comment]
Because it fixes existing installation and doesn't _require_ users to update (nor you'll have to release a new breaking release of `tape-run`)

**Comment by juliangruber** [comment]
Multiple release channels 🤷‍♂ Removing phantomjs is good, let's just let them upgrade. I don't want to go through the work of setting up a multi release channel process yet

**Comment by fregante** [comment]
It’s really not that hard. Let’s not complicate things

**Comment by juliangruber** [comment]
`7.0.0` is out 🎆

**Pull request merged**
