### PR TITLE
Use browser-launcher2.

### PR DESCRIPTION
**Pull request by timoxley**
I've kinda just changed this with a quick fix to make it work for me, I'll probably just bundle it into my app if you don't accept this, so whatever. [browser-launcher2](https://github.com/benderjs/browser-launcher2) resolves the aforementioned [browsers not closing on OS X](https://github.com/substack/browser-launcher/issues/34) issue.

[browser-launcher2](https://github.com/benderjs/browser-launcher2) (in yellow) also seems to have far more activity.

image

image

### CODE REVIEW

**Comment by zeke** [comment]
Hi folks! 👋 

I just tried using browser-run on [an existing smokestack/tap suite](https://github.com/zeke/browser-date-formatter/blob/c8558b6afd49567b07c14a07bbc85cec8eb08255/test/index.js) and ran into this issue where the (chrome) browser window doesn't close.

@juliangruber wanna kick off the travis build again and see if it passes? I tried locally but couldn't get tests to pass, even on the master branch: https://github.com/juliangruber/browser-run/issues/102

**Comment by juliangruber** [comment]
@zeke the browser-run part seems to work for me:

```bash
 ∴  browser-date-formatter ((HEAD detached at c8558b6)) : ./node_modules/.bin/browserify test/index.js | browser-run
TAP version 13
# formatter
ok 1 uses a relative date string by default
not ok 2 supports custom strftime formats
  ---
    operator: equal
    expected: |-
      '2016-04-07'
    actual: |-
      '2016-04-08'
    at: Test.assert [as _assert] (http://localhost:52352/bundle.js:16353:17)
  ...
 ∴  browser-date-formatter ((HEAD detached at c8558b6)) :
```

**Comment by juliangruber** [comment]
@zeke when I change the data assert, it finishes as it should:

```bash
 ∴  browser-date-formatter ((HEAD detached at c8558b6)) : ./node_modules/.bin/browserify test/index.js | browser-run
TAP version 13
# formatter
ok 1 uses a relative date string by default
ok 2 supports custom strftime formats
 ∴  browser-date-formatter ((HEAD detached at c8558b6)) :
```

**Comment by fregante** [comment]
Closing this as slightly stale

**Pull request closed without merging**
