### PR TITLE
Bumping electron-stream to v8.0.0

### PR DESCRIPTION
**Pull request by eklem**
To get a electron version without security issues.

### CODE REVIEW

**Comment by eklem** [comment]
I'll make a PR on tape-run too if/when this is accepted, @juliangruber

**Comment by eklem** [comment]
Also, it needs a version bump, but wasn't sure if this was v7.0.3 in your mind, or something else.

**Comment by juliangruber** [comment]
Thanks for this! It will be a major bump, since it's a major electron version bump.

**Comment by juliangruber** [comment]
https://github.com/juliangruber/browser-run/releases/tag/v8.0.0

**Pull request merged**
