### PR TITLE
Add capability for defining a dynamic mock server

### PR DESCRIPTION
**Pull request by naugtur**
Sometimes you need more than static resources to run your tests against. I needed that for functional-testing xhr

- I didn't add tests for the only reason I accept - I didn't know how. I would if there already was one for --static that I could mimic

### CODE REVIEW

**Comment by juliangruber** [comment]
can you describe a particular use case a bit more, so i can get a feeling for how this would be used? or paste code, even better?

**Comment by naugtur** [comment]
I'm using it already (tried to PR against run-browser, but it's not maintained anymore) here
https://github.com/naugtur/xhr/blob/master/test/mock-server.js

And this is the setup with browser-run on a branch package.json:
"test": "browserify test/index.js | browser-run -m test/mock-server.js | tap-spec",

I'm func-testing XMLHttpRequest related code, so I must control the back-end for mocking and it needs to be on the same origin. 

I imagine this is going to be very useful in other functional test situations, because there's no other way to have a server run with tests and not require adding cross-origin support to the server and app.

**Comment by naugtur** [comment]
Let me know if I need to do anything else to get this upstream.

**Comment by naugtur** [comment]
bump.

I need to switch to browser-run anyway, so please let me know if you're willing to merge this or I need to maintain a fork.

**Comment by juliangruber** [comment]
What about we write an utility that lets you spawn two procs at once, cleaning up after the first finishes and exiting with its exit code. Then your test script could look like this:

```json
  "test": "parallel \"browserify test/index.js | browser-run  | tap-spec\" \"node test/mock-server.js\""
```

**Comment by naugtur** [comment]
Sure, but not with sameorigin policy.
That's why I'm proposing this - so that having a server on the same origin as the script being tested is possible. 

That separate process could proxy to browser-run's server, but then it would have to be able to affect the port number used by browser.

**Comment by naugtur** [comment]
bump.

If you don't want it because it's bloat to you, feel free to tell me to get lost ;)

**Comment by juliangruber** [comment]
published as 3.4.0 wheeee

**Comment by naugtur** [comment]
cool, thx!
I'll be back with some more appealing changes in the future ;)

**Pull request merged**
